# Generated by Django 5.0.6 on 2026-09-15 01:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría de indicador',
                'verbose_name_plural': 'Categorías de indicadores',
            },
        ),
        migrations.CreateModel(
            name='Observatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: OBS-001', max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('departamento', models.CharField(blank=True, max_length=120)),
                ('municipio', models.CharField(blank=True, max_length=120)),
                ('coordinador', models.CharField(blank=True, max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Observatorio',
                'verbose_name_plural': 'Observatorios',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad', models.CharField(blank=True, help_text='Ej: casos, %, personas', max_length=50)),
                ('meta', models.FloatField(blank=True, help_text='Valor de referencia u objetivo', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores', to='core.categoriaindicador')),
                ('observatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='core.observatorio')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ['observatorio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EnvioODK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulario_id', models.CharField(max_length=150)),
                ('envio_id', models.CharField(max_length=150, unique=True)),
                ('datos', models.JSONField()),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('observatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_odk', to='core.observatorio')),
            ],
            options={
                'verbose_name': 'Envío ODK',
                'verbose_name_plural': 'Envíos ODK',
                'ordering': ['-recibido_en'],
            },
        ),
        migrations.CreateModel(
            name='RegistroIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.FloatField()),
                ('fuente', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Coordenada geográfica del registro', null=True, srid=4326)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.indicador')),
            ],
            options={
                'verbose_name': 'Registro de indicador',
                'verbose_name_plural': 'Registros de indicadores',
                'ordering': ['-fecha'],
            },
        ),
    ]
