# Generated by Django 5.0.6 on 2026-09-23 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroindicador',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=12),
        ),
        migrations.AddField(
            model_name='registroindicador',
            name='motivo_rechazo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='registroindicador',
            name='revisado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroindicador',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_revisados', to=settings.AUTH_USER_MODEL),
        ),
    ]
