# Generated by Django 5.0.6 on 2026-09-30 20:54

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_registroindicador_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Para ordenar en los selectores')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de hecho',
                'verbose_name_plural': 'Tipos de hecho',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='observatorio',
        ),
        migrations.RemoveField(
            model_name='registroindicador',
            name='indicador',
        ),
        migrations.RemoveField(
            model_name='registroindicador',
            name='revisado_por',
        ),
        migrations.CreateModel(
            name='CasoVictimizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hecho', models.DateField(verbose_name='Fecha en que ocurrió el hecho')),
                ('vereda_corregimiento_barrio', models.CharField(blank=True, max_length=200)),
                ('zona', models.CharField(blank=True, choices=[('rural', 'Rural'), ('urbana', 'Urbana'), ('centro_poblado', 'Centro poblado')], max_length=20)),
                ('tipo_hecho_otro', models.CharField(blank=True, max_length=200, verbose_name="Especifique (si el tipo de hecho es 'Otro')")),
                ('presunto_responsable', models.CharField(blank=True, choices=[('grupo_armado_organizado', 'Grupo armado organizado'), ('agente_estado', 'Agente del Estado'), ('grupo_no_identificado', 'Grupo armado no identificado'), ('no_identificado', 'No identificado / desconocido'), ('no_aplica', 'No aplica')], max_length=30)),
                ('presunto_responsable_detalle', models.CharField(blank=True, max_length=200)),
                ('num_personas_afectadas', models.PositiveIntegerField(blank=True, null=True)),
                ('num_hombres', models.PositiveIntegerField(blank=True, null=True)),
                ('num_mujeres', models.PositiveIntegerField(blank=True, null=True)),
                ('num_otro_genero', models.PositiveIntegerField(blank=True, null=True)),
                ('num_ninos_adolescentes', models.PositiveIntegerField(blank=True, null=True)),
                ('num_adultos', models.PositiveIntegerField(blank=True, null=True)),
                ('num_adultos_mayores', models.PositiveIntegerField(blank=True, null=True)),
                ('num_familias_afectadas', models.PositiveIntegerField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, max_length=200)),
                ('nivel_verificacion', models.CharField(choices=[('confirmado', 'Confirmado'), ('en_verificacion', 'En proceso de verificación'), ('no_verificado', 'No verificado')], default='no_verificado', max_length=20)),
                ('archivo_soporte', models.FileField(blank=True, null=True, upload_to=core.models._ruta_soporte_caso)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del hecho (sin datos que identifiquen víctimas)')),
                ('afectaciones_materiales', models.TextField(blank=True)),
                ('necesidades_identificadas', models.TextField(blank=True)),
                ('remitido_a', models.CharField(blank=True, max_length=200)),
                ('estado_seguimiento', models.CharField(choices=[('reportado', 'Reportado'), ('en_gestion', 'En gestión'), ('remitido', 'Remitido'), ('cerrado', 'Cerrado')], default='reportado', max_length=20)),
                ('observaciones_seguimiento', models.TextField(blank=True)),
                ('autorizacion_registro', models.BooleanField(default=False, verbose_name='¿Se autorizó expresamente registrar este hecho?')),
                ('requiere_reserva', models.BooleanField(default=True, verbose_name='¿Requiere manejo confidencial/reservado?')),
                ('diligencia_nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre de quien diligencia')),
                ('diligencia_rol', models.CharField(blank=True, max_length=150, verbose_name='Rol de quien diligencia')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=12)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('observatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='core.observatorio')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_revisados', to=settings.AUTH_USER_MODEL)),
                ('tipo_hecho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='core.tipohecho')),
            ],
            options={
                'verbose_name': 'Caso victimizante',
                'verbose_name_plural': 'Casos victimizantes',
                'ordering': ['-fecha_hecho'],
            },
        ),
        migrations.DeleteModel(
            name='CategoriaIndicador',
        ),
        migrations.DeleteModel(
            name='Indicador',
        ),
        migrations.DeleteModel(
            name='RegistroIndicador',
        ),
    ]
