# Generated by Django 5.0.6 on 2026-10-01 02:27

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tipohecho_remove_indicador_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casovictimizante',
            name='archivo_soporte',
            field=models.FileField(blank=True, help_text='PDF, imagen o documento de Word, máximo 10 MB.', null=True, upload_to=core.models._ruta_soporte_caso, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx']), core.models.validar_tamano_archivo_soporte]),
        ),
    ]
